"""
Scheduler Module — Job Search Orchestration System
Santiago Aldana | Executive Job Search

Manages macOS launchd plists:
  - Weekly email digest: every Monday at 8am
  - Gmail monitor: every 30 minutes (continuous job-search email polling)

No cron. launchd handles sleep/wake and persists across reboots.

Usage (via orchestrate.py):
  python3 orchestrate.py schedule install             # Install Monday 8am digest job
  python3 orchestrate.py schedule install-gmail       # Install 30-min Gmail monitor job
  python3 orchestrate.py schedule status              # Check digest scheduler status
  python3 orchestrate.py schedule uninstall           # Remove digest job
  python3 orchestrate.py schedule uninstall-gmail     # Remove Gmail monitor job

To force an immediate test run after installing:
  launchctl start com.jobsearch.digest
  launchctl start com.jobsearch.gmail
  tail -f data/scheduler.log
"""

import subprocess
import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

console = Console()

# ── Config — Digest ───────────────────────────────────────────────────────────

PLIST_LABEL   = "com.jobsearch.digest"
PLIST_PATH    = Path.home() / "Library" / "LaunchAgents" / f"{PLIST_LABEL}.plist"
WRAPPER_SCRIPT = Path.home() / "job-search-digest.sh"

# ── Config — Gmail Monitor ────────────────────────────────────────────────────

GMAIL_PLIST_LABEL  = "com.jobsearch.gmail"
GMAIL_PLIST_PATH   = Path.home() / "Library" / "LaunchAgents" / f"{GMAIL_PLIST_LABEL}.plist"
GMAIL_WRAPPER_SCRIPT = Path.home() / "job-search-gmail.sh"

# ── Config — LinkedIn Publisher ───────────────────────────────────────────────

LI_PLIST_LABEL     = "com.jobsearch.linkedin"
LI_PLIST_PATH      = Path.home() / "Library" / "LaunchAgents" / f"{LI_PLIST_LABEL}.plist"
LI_WRAPPER_SCRIPT  = Path.home() / "job-search-linkedin.sh"

# Absolute path to project root (two levels up from this file)
PROJECT_DIR = Path(__file__).parent.parent.resolve()
LOG_PATH    = PROJECT_DIR / "data" / "scheduler.log"
GMAIL_LOG_PATH = PROJECT_DIR / "data" / "gmail_scheduler.log"
LI_LOG_PATH = PROJECT_DIR / "data" / "linkedin_scheduler.log"


# ── Plist Builder ─────────────────────────────────────────────────────────────

def build_wrapper_script(project_dir: Path, log_path: Path) -> str:
    """
    A small shell script that lives in ~ (home directory).

    The plist calls this script via osascript, which runs in the user's
    GUI session and has full access to OneDrive/iCloud Drive paths without
    needing Full Disk Access granted to python3 or bash.
    """
    work_dir = str(project_dir)
    orchestrate = str(project_dir / "orchestrate.py")
    log = str(log_path)
    return f"""#!/bin/bash
# Job Search Digest — weekly email automation launcher
# Generated by skills/scheduler.py — do not edit manually.
# Called via osascript so it runs in the user's GUI session,
# inheriting access to OneDrive paths without Full Disk Access.

set -euo pipefail

LOG="{log}"
mkdir -p "$(dirname "$LOG")"

echo "--- $(date) ---" >> "$LOG"
cd "{work_dir}"
/usr/bin/python3 "{orchestrate}" digest --no-enrich >> "$LOG" 2>&1
echo "[Done]" >> "$LOG"
"""


def build_plist_xml(wrapper_script: Path, log_path: Path) -> str:
    """
    Render the launchd plist XML string.

    Uses osascript to run the wrapper shell script in the user's GUI session.
    This bypasses TCC restrictions on OneDrive/iCloud Drive paths that block
    standard launchd agents — osascript always runs with the logged-in user's
    full folder-access permissions.

    StartCalendarInterval: Monday (Weekday=1) at 08:00.
    RunAtLoad: false.
    """
    log = str(log_path)
    # osascript command: run shell script "bash /path/to/wrapper.sh"
    applescript = f'do shell script "bash \\"{wrapper_script}\\""'

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{PLIST_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/osascript</string>
        <string>-e</string>
        <string>{applescript}</string>
    </array>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key>
        <integer>1</integer>
        <key>Hour</key>
        <integer>8</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>{log}</string>

    <key>StandardErrorPath</key>
    <string>{log}</string>
</dict>
</plist>
"""


# ── Install / Uninstall / Status ──────────────────────────────────────────────

def install() -> None:
    """Write the wrapper script + plist, then register with launchctl."""
    # Ensure data/ dir exists for the log
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

    # 1. Write the wrapper script to ~ (always accessible by launchd)
    wrapper_sh = build_wrapper_script(PROJECT_DIR, LOG_PATH)
    WRAPPER_SCRIPT.write_text(wrapper_sh, encoding="utf-8")
    WRAPPER_SCRIPT.chmod(0o755)
    console.print(f"[dim]Wrapper script written to {WRAPPER_SCRIPT}[/dim]")

    # 2. Build and write the plist (points at the wrapper, not OneDrive)
    plist_xml = build_plist_xml(WRAPPER_SCRIPT, LOG_PATH)

    # If already loaded, unload first to apply changes
    existing = subprocess.run(
        ["launchctl", "list", PLIST_LABEL],
        capture_output=True, text=True
    )
    if existing.returncode == 0:
        console.print("[yellow]Job already registered — reloading with updated config...[/yellow]")
        subprocess.run(["launchctl", "unload", str(PLIST_PATH)], capture_output=True)

    PLIST_PATH.write_text(plist_xml, encoding="utf-8")
    console.print(f"[dim]Plist written to {PLIST_PATH}[/dim]")

    result = subprocess.run(
        ["launchctl", "load", str(PLIST_PATH)],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        console.print(f"[red]launchctl load failed: {result.stderr.strip()}[/red]")
        return

    console.print(Panel(
        f"[bold green]Scheduler installed.[/bold green]\n\n"
        f"Job label     : [cyan]{PLIST_LABEL}[/cyan]\n"
        f"Schedule      : Every Monday at 08:00\n"
        f"Wrapper script: {WRAPPER_SCRIPT}\n"
        f"Log file      : {LOG_PATH}\n\n"
        f"[dim]To test immediately:[/dim]\n"
        f"  launchctl start {PLIST_LABEL}\n"
        f"  tail -f \"{LOG_PATH}\"",
        border_style="green",
        title="Schedule Installed"
    ))


def uninstall() -> None:
    """Unload and delete the plist."""
    if not PLIST_PATH.exists():
        console.print(f"[yellow]Plist not found at {PLIST_PATH} — nothing to remove.[/yellow]")
        return

    result = subprocess.run(
        ["launchctl", "unload", str(PLIST_PATH)],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        console.print(f"[yellow]launchctl unload warning: {result.stderr.strip()}[/yellow]")

    PLIST_PATH.unlink()

    # Also remove the wrapper script from ~
    if WRAPPER_SCRIPT.exists():
        WRAPPER_SCRIPT.unlink()
        wrapper_msg = f"Wrapper script deleted: {WRAPPER_SCRIPT}"
    else:
        wrapper_msg = ""

    console.print(Panel(
        f"[bold]Scheduler removed.[/bold]\n"
        f"Plist deleted  : {PLIST_PATH}\n"
        + (f"{wrapper_msg}" if wrapper_msg else ""),
        border_style="yellow",
        title="Schedule Uninstalled"
    ))


def status() -> None:
    """Check launchd registration and next scheduled run."""
    table = Table(title="Scheduler Status", box=box.ROUNDED)
    table.add_column("Property", style="bold")
    table.add_column("Value")

    # launchctl list
    result = subprocess.run(
        ["launchctl", "list", PLIST_LABEL],
        capture_output=True, text=True
    )

    if result.returncode == 0:
        registered = "[green]Registered[/green]"
        # Parse PID from output (first column)
        lines = result.stdout.strip().splitlines()
        pid_line = lines[0] if lines else ""
        pid = pid_line.split()[0] if pid_line else "-"
        pid_display = f"[green]Running (PID {pid})[/green]" if pid.isdigit() else "[dim]Not currently running[/dim]"
    else:
        registered = "[red]Not registered[/red]"
        pid_display = "[dim]—[/dim]"

    plist_exists   = "[green]Yes[/green]" if PLIST_PATH.exists() else "[red]Missing[/red]"
    wrapper_exists = "[green]Yes[/green]" if WRAPPER_SCRIPT.exists() else "[red]Missing[/red]"
    log_exists     = str(LOG_PATH) if LOG_PATH.exists() else "[dim]No log yet[/dim]"

    table.add_row("Job label",      PLIST_LABEL)
    table.add_row("Registered",     registered)
    table.add_row("Process",        pid_display)
    table.add_row("Schedule",       "Every Monday at 08:00")
    table.add_row("Plist file",     plist_exists)
    table.add_row("Wrapper script", wrapper_exists)
    table.add_row("Log file",       log_exists)

    console.print(table)

    # Show last 10 lines of log if it exists
    if LOG_PATH.exists():
        log_lines = LOG_PATH.read_text(encoding="utf-8", errors="replace").splitlines()
        if log_lines:
            console.print("\n[bold]Last log entries:[/bold]")
            for line in log_lines[-10:]:
                console.print(f"  [dim]{line}[/dim]")

    if result.returncode != 0:
        console.print(
            f"\n[yellow]Not installed. Run:[/yellow] "
            f"[cyan]python3 orchestrate.py schedule install[/cyan]"
        )
    else:
        console.print(
            f"\n[dim]To force an immediate run:[/dim] "
            f"[cyan]launchctl start {PLIST_LABEL}[/cyan]"
        )


# ── Gmail Monitor Scheduler ───────────────────────────────────────────────────

def _build_gmail_wrapper_script(project_dir: Path, log_path: Path) -> str:
    """Wrapper script for the 30-min Gmail monitor job."""
    work_dir = str(project_dir)
    orchestrate = str(project_dir / "orchestrate.py")
    log = str(log_path)
    return f"""#!/bin/bash
# Job Search Gmail Monitor — 30-minute automation launcher
# Generated by skills/scheduler.py — do not edit manually.

set -euo pipefail

LOG="{log}"
mkdir -p "$(dirname "$LOG")"

echo "--- $(date) ---" >> "$LOG"
cd "{work_dir}"
/usr/bin/python3 "{orchestrate}" gmail scan >> "$LOG" 2>&1
echo "[Done]" >> "$LOG"
"""


def _build_gmail_plist_xml(wrapper_script: Path, log_path: Path) -> str:
    """Render the Gmail monitor launchd plist — runs every 30 minutes."""
    log = str(log_path)
    applescript = f'do shell script "bash \\"{wrapper_script}\\""'
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{GMAIL_PLIST_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/osascript</string>
        <string>-e</string>
        <string>{applescript}</string>
    </array>

    <key>StartInterval</key>
    <integer>1800</integer>

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>{log}</string>

    <key>StandardErrorPath</key>
    <string>{log}</string>
</dict>
</plist>
"""


def install_gmail() -> None:
    """Install the 30-minute Gmail monitor launchd job."""
    GMAIL_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

    wrapper_sh = _build_gmail_wrapper_script(PROJECT_DIR, GMAIL_LOG_PATH)
    GMAIL_WRAPPER_SCRIPT.write_text(wrapper_sh, encoding="utf-8")
    GMAIL_WRAPPER_SCRIPT.chmod(0o755)
    console.print(f"[dim]Wrapper script written to {GMAIL_WRAPPER_SCRIPT}[/dim]")

    plist_xml = _build_gmail_plist_xml(GMAIL_WRAPPER_SCRIPT, GMAIL_LOG_PATH)

    existing = subprocess.run(
        ["launchctl", "list", GMAIL_PLIST_LABEL],
        capture_output=True, text=True
    )
    if existing.returncode == 0:
        console.print("[yellow]Gmail job already registered — reloading...[/yellow]")
        subprocess.run(["launchctl", "unload", str(GMAIL_PLIST_PATH)], capture_output=True)

    GMAIL_PLIST_PATH.write_text(plist_xml, encoding="utf-8")
    result = subprocess.run(
        ["launchctl", "load", str(GMAIL_PLIST_PATH)],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        console.print(f"[red]launchctl load failed: {result.stderr.strip()}[/red]")
        return

    console.print(Panel(
        f"[bold green]Gmail Monitor installed.[/bold green]\n\n"
        f"Job label     : [cyan]{GMAIL_PLIST_LABEL}[/cyan]\n"
        f"Schedule      : Every 30 minutes\n"
        f"Wrapper script: {GMAIL_WRAPPER_SCRIPT}\n"
        f"Log file      : {GMAIL_LOG_PATH}\n\n"
        f"[dim]Prerequisites:[/dim]\n"
        f"  1. GMAIL_ACCOUNT_1 / GMAIL_ACCOUNT_2 set in .env\n"
        f"  2. ~/.job-search-gmail/credentials.json in place\n"
        f"  3. Run: [cyan]python3 orchestrate.py gmail auth[/cyan]\n\n"
        f"[dim]To test immediately:[/dim]\n"
        f"  launchctl start {GMAIL_PLIST_LABEL}\n"
        f"  tail -f \"{GMAIL_LOG_PATH}\"",
        border_style="green",
        title="Gmail Monitor Installed"
    ))


def uninstall_gmail() -> None:
    """Unload and delete the Gmail monitor plist."""
    if not GMAIL_PLIST_PATH.exists():
        console.print(f"[yellow]Plist not found at {GMAIL_PLIST_PATH} — nothing to remove.[/yellow]")
        return

    subprocess.run(["launchctl", "unload", str(GMAIL_PLIST_PATH)], capture_output=True)
    GMAIL_PLIST_PATH.unlink()

    if GMAIL_WRAPPER_SCRIPT.exists():
        GMAIL_WRAPPER_SCRIPT.unlink()

    console.print(Panel(
        f"[bold]Gmail Monitor removed.[/bold]\n"
        f"Plist deleted: {GMAIL_PLIST_PATH}",
        border_style="yellow",
        title="Gmail Monitor Uninstalled"
    ))


# ── LinkedIn Publisher Scheduler ──────────────────────────────────────────────

def _build_linkedin_wrapper_script(project_dir: Path, log_path: Path) -> str:
    """Wrapper script for the 30-min LinkedIn publish job."""
    work_dir    = str(project_dir)
    orchestrate = str(project_dir / "orchestrate.py")
    log         = str(log_path)
    return f"""#!/bin/bash
# Job Search LinkedIn Publisher — 30-minute automation launcher
# Generated by skills/scheduler.py — do not edit manually.

set -euo pipefail

LOG="{log}"
mkdir -p "$(dirname "$LOG")"

echo "--- $(date) ---" >> "$LOG"
cd "{work_dir}"
/usr/bin/python3 "{orchestrate}" linkedin publish >> "$LOG" 2>&1
echo "[Done]" >> "$LOG"
"""


def _build_linkedin_plist_xml(wrapper_script: Path, log_path: Path) -> str:
    """Render the LinkedIn publisher launchd plist — runs every 30 minutes."""
    log = str(log_path)
    applescript = f'do shell script "bash \\"{wrapper_script}\\""'
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LI_PLIST_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/osascript</string>
        <string>-e</string>
        <string>{applescript}</string>
    </array>

    <key>StartInterval</key>
    <integer>1800</integer>

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>{log}</string>

    <key>StandardErrorPath</key>
    <string>{log}</string>
</dict>
</plist>
"""


def install_linkedin() -> None:
    """Install the 30-minute LinkedIn publisher launchd job."""
    LI_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

    wrapper_sh = _build_linkedin_wrapper_script(PROJECT_DIR, LI_LOG_PATH)
    LI_WRAPPER_SCRIPT.write_text(wrapper_sh, encoding="utf-8")
    LI_WRAPPER_SCRIPT.chmod(0o755)
    console.print(f"[dim]Wrapper script written to {LI_WRAPPER_SCRIPT}[/dim]")

    plist_xml = _build_linkedin_plist_xml(LI_WRAPPER_SCRIPT, LI_LOG_PATH)

    existing = subprocess.run(
        ["launchctl", "list", LI_PLIST_LABEL],
        capture_output=True, text=True
    )
    if existing.returncode == 0:
        console.print("[yellow]LinkedIn job already registered — reloading...[/yellow]")
        subprocess.run(["launchctl", "unload", str(LI_PLIST_PATH)], capture_output=True)

    LI_PLIST_PATH.write_text(plist_xml, encoding="utf-8")
    result = subprocess.run(
        ["launchctl", "load", str(LI_PLIST_PATH)],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        console.print(f"[red]launchctl load failed: {result.stderr.strip()}[/red]")
        return

    console.print(Panel(
        f"[bold green]LinkedIn Publisher installed.[/bold green]\n\n"
        f"Job label     : [cyan]{LI_PLIST_LABEL}[/cyan]\n"
        f"Schedule      : Every 30 minutes\n"
        f"Wrapper script: {LI_WRAPPER_SCRIPT}\n"
        f"Log file      : {LI_LOG_PATH}\n\n"
        f"[dim]Prerequisites:[/dim]\n"
        f"  1. LINKEDIN_CLIENT_ID + LINKEDIN_CLIENT_SECRET set in .env\n"
        f"  2. Run: [cyan]python3 orchestrate.py linkedin auth[/cyan]\n\n"
        f"[dim]To test immediately:[/dim]\n"
        f"  launchctl start {LI_PLIST_LABEL}\n"
        f"  tail -f \"{LI_LOG_PATH}\"",
        border_style="green",
        title="LinkedIn Publisher Installed"
    ))


def uninstall_linkedin() -> None:
    """Unload and delete the LinkedIn publisher plist."""
    if not LI_PLIST_PATH.exists():
        console.print(f"[yellow]Plist not found at {LI_PLIST_PATH} — nothing to remove.[/yellow]")
        return

    subprocess.run(["launchctl", "unload", str(LI_PLIST_PATH)], capture_output=True)
    LI_PLIST_PATH.unlink()

    if LI_WRAPPER_SCRIPT.exists():
        LI_WRAPPER_SCRIPT.unlink()

    console.print(Panel(
        f"[bold]LinkedIn Publisher removed.[/bold]\n"
        f"Plist deleted: {LI_PLIST_PATH}",
        border_style="yellow",
        title="LinkedIn Publisher Uninstalled"
    ))
